### PR TITLE
enhance generic `Bundle` easyblock to transfer module requirements of components, but do not create logfile in components

### PR DESCRIPTION
**Pull request by Thyre**
This fixes the increased disk usage when running the EasyConfig test suite as log files would stay open.
See https://github.com/easybuilders/easybuild-easyconfigs/issues/21841 for more information.

Requires:
- [x] https://github.com/easybuilders/easybuild-framework/pull/4707

Related:
- https://github.com/easybuilders/easybuild-easyconfigs/issues/21841

See #3472 for the initial review and #3504 for the occurring issue, causing a revert of the PR.

### CODE REVIEW

**Comment by Thyre** [comment]
Test report by @Thyre
"Can't find path /home/jreuter/Autotools/20231222-GCCcore-13.3.0"
Failed during parsing of the easyconfigs, so no ecs were built (2 easyconfigs in total)
Linux - Linux EndeavourOS UNKNOWN, x86_64, AMD Ryzen 7 7800X3D 8-Core Processor, 1 x NVIDIA NVIDIA GeForce RTX 3070, 565.57.01, Python 3.12.7
See https://gist.github.com/Thyre/6b5c12b9d97f95ebfd9eaf89b8bc663c for a full test report.

**Comment by Thyre** [comment]
Test report by @Thyre
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GCC-13.3.0.eb_ 
 * **SUCCESS** _Autotools-20231222-GCCcore-13.3.0.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
Linux - Linux EndeavourOS UNKNOWN, x86_64, AMD Ryzen 7 7800X3D 8-Core Processor, 1 x NVIDIA NVIDIA GeForce RTX 3070, 565.57.01, Python 3.12.7
See https://gist.github.com/Thyre/91835076bbb9bad8921c1b8608402863 for a full test report.

**Comment by Thyre** [comment]
Test report by @Thyre
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _buildenv-default-foss-2023b.eb_ 
 * **SUCCESS** _OpenSSL-3.eb_ 
 * **SUCCESS** _Circuitscape-5.12.3-Julia-1.9.2.eb_ 
 * **SUCCESS** _Perl-bundle-CPAN-5.38.2-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _gfbf-2024a.eb_ 
 * **SUCCESS** _crypt4gh-1.7-GCC-12.3.0.eb_ 
 * **SUCCESS** _GCC-system.eb_ 
 * **SUCCESS** _jiter-0.4.1-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _X11-20240607-GCCcore-13.3.0.eb_ 
 * **FAIL (build issue)** _GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/6f3d91d68baa3c97cfa6d9ed2683e5ad)
 * **FAIL (build issue)** _zlib-1.2.11-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/e541a256d17e7d3715aecff84ddcd3f9)
 * **FAIL (build issue)** _help2man-1.47.4-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/7c36d43e230398aeb56e3302b60cb00e)
 * **FAIL (build issue)** _M4-1.4.18-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/9cb1e0636cdccc6c62f4f001875cb45d)
 * **FAIL (build issue)** _Bison-3.0.4-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/fe629550dd9f592436576ea79ec71176)
 * **FAIL (build issue)** _Bison-3.0.5-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/4b424dad19836326ce8fb3c2e5aa8ca3)
 * **FAIL (build issue)** _flex-2.6.4-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/43223f50e4d0c4f8dad64299831388fa)
 * **FAIL (build issue)** _binutils-2.29-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/7e2d5975ec8ca2b202a330e0b1d6881e)
 * **FAIL (build issue)** _GCC-system-2.29.eb_ (partial log available at https://gist.github.com/Thyre/6e226ad1fb92a1026d9c1dfdee56bd89)
 * **FAIL (build issue)** _OpenMPI-system-GCC-system-2.29.eb_ (partial log available at https://gist.github.com/Thyre/7eccf5edc389270d4acef962053f247c)

Build succeeded for 9 out of 19 (10 easyconfigs in total)
datenlager - Linux Ubuntu 24.04, x86_64, AMD Ryzen 7 3700X 8-Core Processor, Python 3.12.3
See https://gist.github.com/Thyre/1f2efb9ca0b89f91030fc316828e19d2 for a full test report.

**Comment by Thyre** [comment]
> Test report by @Thyre
> #### Overview of tested easyconfigs (in order)
> 
>     * **SUCCESS** _buildenv-default-foss-2023b.eb_
> 
>     * **SUCCESS** _OpenSSL-3.eb_
> 
>     * **SUCCESS** _Circuitscape-5.12.3-Julia-1.9.2.eb_
> 
>     * **SUCCESS** _Perl-bundle-CPAN-5.38.2-GCCcore-13.3.0.eb_
> 
>     * **SUCCESS** _gfbf-2024a.eb_
> 
>     * **SUCCESS** _crypt4gh-1.7-GCC-12.3.0.eb_
> 
>     * **SUCCESS** _GCC-system.eb_
> 
>     * **SUCCESS** _jiter-0.4.1-GCCcore-12.3.0.eb_
> 
>     * **SUCCESS** _X11-20240607-GCCcore-13.3.0.eb_
> 
>     * **FAIL (build issue)** _GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/6f3d91d68baa3c97cfa6d9ed2683e5ad)
> 
>     * **FAIL (build issue)** _zlib-1.2.11-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/e541a256d17e7d3715aecff84ddcd3f9)
> 
>     * **FAIL (build issue)** _help2man-1.47.4-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/7c36d43e230398aeb56e3302b60cb00e)
> 
>     * **FAIL (build issue)** _M4-1.4.18-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/9cb1e0636cdccc6c62f4f001875cb45d)
> 
>     * **FAIL (build issue)** _Bison-3.0.4-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/fe629550dd9f592436576ea79ec71176)
> 
>     * **FAIL (build issue)** _Bison-3.0.5-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/4b424dad19836326ce8fb3c2e5aa8ca3)
> 
>     * **FAIL (build issue)** _flex-2.6.4-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/43223f50e4d0c4f8dad64299831388fa)
> 
>     * **FAIL (build issue)** _binutils-2.29-GCCcore-system.eb_ (partial log available at https://gist.github.com/Thyre/7e2d5975ec8ca2b202a330e0b1d6881e)
> 
>     * **FAIL (build issue)** _GCC-system-2.29.eb_ (partial log available at https://gist.github.com/Thyre/6e226ad1fb92a1026d9c1dfdee56bd89)
> 
>     * **FAIL (build issue)** _OpenMPI-system-GCC-system-2.29.eb_ (partial log available at https://gist.github.com/Thyre/7eccf5edc389270d4acef962053f247c)
> 
> 
> Build succeeded for 9 out of 19 (10 easyconfigs in total) datenlager - Linux Ubuntu 24.04, x86_64, AMD Ryzen 7 3700X 8-Core Processor, Python 3.12.3 See https://gist.github.com/Thyre/1f2efb9ca0b89f91030fc316828e19d2 for a full test report.

Failures due to https://github.com/easybuilders/easybuild-easyblocks/pull/3402 missing.

```
== 2024-11-15 09:07:43,949 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): No viable license specifications found; specify 'license_file', or define $INTEL_LICENSE_FILE or $LM_LICENSE_FILE (at easybuild/easyblocks/generic/intelbase.py:308 in prepare_step)
```

File: easybuild/easyblocks/generic/bundle.py [hunk 1]
```diff
@@ -321,8 +320,37 @@ def install_step(self):
                             new_val = path
                         env.setvar(envvar, new_val)
 
-            # close log for this component
-            comp.close_log()
```
Comment (Thyre) [inline easybuild/easyblocks/generic/bundle.py:325]: We should make sure that this removal is safe. Based on the changes in framework I think it is, as the components just use the log file of the Bundle. Keeping it in doesn't hurt though, as the changes in framework should make sure that only Bundle can close its log and none of the components.

Comment (boegel) [reply easybuild/easyblocks/generic/bundle.py:325]: I don't see the point in keeping this, it's clear that the component shouldn't be closing the log now since it's using the "parent" log provided by the `Bundle` instance.

File: easybuild/easyblocks/generic/bundle.py [hunk 2]
```diff
@@ -321,8 +320,37 @@ def install_step(self):
...
+    def make_module_req_guess(self):
+        """
+        Set module requirements from all comppnents, e.g. $PATH, etc.
```
Comment (boegel) [inline easybuild/easyblocks/generic/bundle.py:325]: typo:
```suggestion
        Set module requirements from all components, e.g. $PATH, etc.

File: easybuild/easyblocks/generic/bundle.py [hunk 3]
```diff
@@ -321,8 +320,37 @@ def install_step(self):
...
+        During the install step, we only set these requirements temporarily.
+        Later on when building the module, those paths are not considered.
+        Therefore, iterate through all the components again and gather
+        the requirements.
+
+        Do not remove duplicates or check for existance of folders,
```
Comment (boegel) [inline easybuild/easyblocks/generic/bundle.py:331]: typo:
```suggestion
        Do not remove duplicates or check for existence of folders,

File: easybuild/easyblocks/generic/bundle.py [hunk 4]
```diff
@@ -321,8 +320,37 @@ def install_step(self):
...
+        as this is done in the generic EasyBlock while creating
+        the modulefile already.
```
Comment (boegel) [inline easybuild/easyblocks/generic/bundle.py:333]: typo:
```suggestion
        the module file already.

File: easybuild/easyblocks/generic/bundle.py [hunk 5]
```diff
@@ -321,8 +320,37 @@ def install_step(self):
...
+        # If not added here, they might be missing entirely and fail sanity checks.
+        final_reqs = super(Bundle, self).make_module_req_guess()
+
+        for cfg, comp in self.comp_instances:
+            self.log.info("Gathering module paths for component %s v%s", cfg['name'], cfg['version'])
+            reqs = comp.make_module_req_guess()
+
+            try:
+                for key, value in sorted(reqs.items()):
+                    if isinstance(reqs, string_type):
```
Comment (boegel) [inline easybuild/easyblocks/generic/bundle.py:345]: @Thyre This seems wrong? Should be:

```suggestion
                    if isinstance(value, string_type):

File: easybuild/easyblocks/generic/bundle.py [hunk 6]
```diff
@@ -321,8 +320,37 @@ def install_step(self):
...
+                        value = [value]
+                    final_reqs.setdefault(key, [])
+                    final_reqs[key] += value
```
Comment (boegel) [inline easybuild/easyblocks/generic/bundle.py:348]: Let's be more explicit that we're dealing with a list here:
```suggestion
                    final_reqs[key].append(value)

File: easybuild/easyblocks/generic/bundle.py [hunk 7]
```diff
@@ -321,8 +320,37 @@ def install_step(self):
...
+            except AttributeError:
```
Comment (boegel) [inline easybuild/easyblocks/generic/bundle.py:349]: Hmm, when would we see an `AttributeError` here exactly?

If this is meant to catch the case where `make_module_req_guess` is somehow not defined for that component, then the call to `comp.make_module_req_guess` should be inside the `try`?

**Review by boegel — CHANGES_REQUESTED** [review]

File: easybuild/easyblocks/generic/bundle.py (hunk 7 above)
Comment (Thyre) [reply easybuild/easyblocks/generic/bundle.py:349]: The main idea is to bail out if an EasyBlock does not pass a `dict` for some reason when we gather the requiements with `comp.make_module_req_guess`, see https://github.com/easybuilders/easybuild-easyblocks/pull/3472#discussion_r1834361337

Comment (Thyre) [reply easybuild/easyblocks/generic/bundle.py:349]: I can add a comment to this, just so that it is clear to a future reader why we catch this exception.

Comment (Thyre) [reply easybuild/easyblocks/generic/bundle.py:352]: Added a comment and rebased to current `develop`.

File: easybuild/easyblocks/generic/bundle.py [hunk 8]
```diff
@@ -321,8 +320,40 @@ def install_step(self):
...
+
+            # Try-except block to fail with an easily understandable error message.
+            # This should only trigger when an EasyBlock returns non-dict module requirements
+            # for make_module_req_guess() which should then be fixed in the components EasyBlock.
+            try:
+                for key, value in sorted(reqs.items()):
+                    if isinstance(value, string_type):
+                        value = [value]
+                    final_reqs.setdefault(key, [])
+                    final_reqs[key].append(value)
```
Comment (Thyre) [inline easybuild/easyblocks/generic/bundle.py:351]: This change breaks the build
```python
>>> a = {}
>>> a.setdefault(1, [])
[]
>>> a[1].append([2])
>>> a[1]
[[2]]
>>> a = {}
>>> a.setdefault(1, [])
[]
>>> a[1] += [2]
>>> a[1]
[2]
>>> 
```

**Comment by Thyre** [comment]
Test report by @Thyre
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _FlexiBLAS-3.3.1-GCC-12.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
datenlager - Linux Ubuntu 24.04, x86_64, AMD Ryzen 7 3700X 8-Core Processor, Python 3.12.3
See https://gist.github.com/Thyre/d3a7d60b320f3bcb317d4c55d0b79166 for a full test report.

**Comment by Thyre** [comment]
Test report by @Thyre
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _buildenv-default-foss-2023b.eb_ 
 * **SUCCESS** _OpenSSL-3.eb_ 
 * **SUCCESS** _Circuitscape-5.12.3-Julia-1.9.2.eb_ 
 * **SUCCESS** _Perl-bundle-CPAN-5.38.2-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _gfbf-2024a.eb_ 
 * **SUCCESS** _crypt4gh-1.7-GCC-12.3.0.eb_ 
 * **SUCCESS** _jiter-0.4.1-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _X11-20240607-GCCcore-13.3.0.eb_ 

Build succeeded for 8 out of 8 (8 easyconfigs in total)
datenlager - Linux Ubuntu 24.04, x86_64, AMD Ryzen 7 3700X 8-Core Processor, Python 3.12.3
See https://gist.github.com/Thyre/3e6e109c6a568293be8b285416d628af for a full test report.

**Comment by Thyre** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="buildenv-default-foss-2023b.eb  OpenSSL-3.eb Circuitscape-5.12.3-Julia-1.9.2.eb Perl-bundle-CPAN-5.38.2-GCCcore-13.3.0.eb gfbf-2024a.eb crypt4gh-1.7-GCC-12.3.0.eb jiter-0.4.1-GCCcore-12.3.0.eb X11-20240607-GCCcore-13.3.0.eb Clang-AOMP-4.5.0-GCCcore-11.2.0.eb"

**Comment by Thyre** [comment]
>     * **FAIL (build issue)** _Clang-AOMP-4.5.0-GCCcore-11.2.0.eb_ (partial log available at https://gist.github.com/boegelbot/d82fb4858e7f8509d04629748780597a)
> 
> 
> Build succeeded for 9 out of 10 (9 easyconfigs in total) jsczen3c1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.5, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.19 See https://gist.github.com/boegelbot/6f439391fecc47536c2a2c3e0be99993 for a full test report.

The gist unfortunately did not include the error. Checking on `jsc-zen3` directly, I see the following error message:
```
/dev/shm/reuter1/ClangAOMP/4.5.0/GCCcore-11.2.0/llvm-project-rocm-4.5.0/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:146:10: fatal error: linux/cyclades.h: No such file or directory
  146 | #include <linux/cyclades.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/build.make:345: projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/sanitizer_platform_limits_posix.cpp.o] Error 1
make[2]: Leaving directory '/dev/shm/reuter1/ClangAOMP/4.5.0/GCCcore-11.2.0/easybuild_obj'
make[1]: *** [CMakeFiles/Makefile2:21910: projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

This looks unrelated to the changes in this PR.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="Clang-AOMP-4.5.0-GCCcore-11.2.0.eb "

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Clang-AOMP-4.5.0-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _matplotlib-3.8.2-gfbf-2023b.eb_ 
 * **SUCCESS** _FlexiBLAS-3.3.1-GCC-12.3.0.eb_ 
 * **SUCCESS** _X11-20231019-GCCcore-13.2.0.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
node4001.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/eaa3dac9f747beb8e6056f01203da28b for a full test report.
